version: "3.9"

services:
  vllm-server:
    image: vllm/vllm-openai:v0.8.0
    container_name: vllm-server
    ports:
      - "8000:8000"
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./models:/app/local_model
    command: >
      --model /app/local_model/3.1-8b-instruct
      --max-model-len 8192
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
