# Kubeadm HA configuration for first control-plane node (pc1)
# This includes API server and etcd certificates SANs for pc3 and pc5

apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "192.168.1.1"   # IP of this control-plane node (pc1)
  bindPort: 6443
nodeRegistration:
  name: "pc1"
  criSocket: "unix:///var/run/containerd/containerd.sock"
  taints:
    - key: "node-role.kubernetes.io/control-plane"
      effect: "NoSchedule"

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: "v1.30.5"
clusterName: "gpt-cluster"

# HA control plane endpoint (VIP of HAProxy + Keepalived)
controlPlaneEndpoint: "192.168.1.100:6443"

# API server certificates: include VIP + all control-plane IPs
apiServer:
  certSANs:
    - "192.168.1.100"   # VIP (HAProxy)
    - "192.168.1.1"     # pc1
    - "192.168.1.3"     # pc3
    - "192.168.1.5"     # pc5
    - "192.168.1.9"     # HAProxy 1
    - "192.168.1.10"    # HAProxy 2
  timeoutForControlPlane: 4m0s

controllerManager: {}
scheduler: {}

# Networking configuration for Flannel CNI
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"

# etcd configuration: include all control-plane nodes for peer/server certs
etcd:
  local:
    serverCertSANs:
      - "pc1"
      - "pc3"
      - "pc5"
      - "192.168.1.1"
      - "192.168.1.3"
      - "192.168.1.5"
      - "localhost"
      - "127.0.0.1"
    peerCertSANs:
      - "pc1"
      - "pc3"
      - "pc5"
      - "192.168.1.1"
      - "192.168.1.3"
      - "192.168.1.5"
      - "localhost"
      - "127.0.0.1"

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: "systemd"
