---
galaxy_info:
  author: Jagz
  description: Install Docker Engine, CLI, and related plugins on Ubuntu
  license: MIT
  min_ansible_version: 2.14
  platforms:
    - name: Ubuntu
      versions:
        - all
dependencies: []
